# Utiliza Oracle Linux 8 como imagen base
FROM oraclelinux:8

# Instala las herramientas necesarias para compilar rlwrap
RUN dnf install -y gcc make readline-devel \
    && dnf install -y oracle-instantclient-release-el8 \
    && dnf install -y oracle-instantclient-basic oracle-instantclient-sqlplus

# Descarga, compila e instala rlwrap
RUN curl -LO https://github.com/hanslub42/rlwrap/releases/download/v0.45.2/rlwrap-0.45.2.tar.gz \
    && tar -xzf rlwrap-0.45.2.tar.gz \
    && cd rlwrap-0.45.2 \
    && ./configure \
    && make \
    && make install \
    && cd .. \
    && rm -rf rlwrap-0.45.2 rlwrap-0.45.2.tar.gz

# Añade un alias para sqlplus con rlwrap
RUN echo "alias sqlplus='rlwrap sqlplus'" >> /root/.bashrc

# Establece el directorio de trabajo
WORKDIR /root

# Comando por defecto al iniciar el contenedor
CMD ["/bin/bash"]
