version: "3"
services:
  oracledb:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    volumes:
      - oracle_data_volume:/opt/oracle/
    ports:
      - 1521:1521
    environment:
      - ORACLE_PWD=${ORACLE_PASSWORD}

  admin:
    build: ./.admin/  # Carpeta donde está el Dockerfile de admin
    depends_on:
      - oracledb
    stdin_open: true
    tty: true

volumes:
  oracle_data_volume:
